# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oa_i13MDm7241hNVu4H7D_7eh5sIfcaQ
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# from sqlalchemy import create_engine, text
# 
# # Load data
# df = pd.DataFrame({
#     "id":[1,2,3,4],
#     "amount":[100,200,150,300],
#     "state":["CA","NY","TX","CA"],
#     "category":["fraud","normal","fraud","normal"]
# })
# 
# # Create database
# engine = create_engine("sqlite:///data.db")
# df.to_sql("transactions", engine, if_exists="replace", index=False)
# 
# # SQL generator (AI simulation)
# def generate_sql(question):
#     q = question.lower()
#     if "total" in q and "state" in q:
#         return "SELECT state, SUM(amount) as total FROM transactions GROUP BY state"
#     elif "fraud" in q:
#         return "SELECT * FROM transactions WHERE category='fraud'"
#     elif "average" in q:
#         return "SELECT AVG(amount) FROM transactions"
#     else:
#         return "SELECT * FROM transactions"
# 
# # UI
# st.title("🤖 AI Data Copilot")
# 
# question = st.text_input("Ask your question")
# 
# if st.button("Run"):
#     sql = generate_sql(question)
# 
#     with engine.connect() as conn:
#         result = conn.execute(text(sql)).fetchall()
# 
#     st.subheader("Generated SQL")
#     st.code(sql)
# 
#     st.subheader("Result")
#     st.write(result)