# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oa_i13MDm7241hNVu4H7D_7eh5sIfcaQ
"""

import streamlit as st
import pandas as pd
from sqlalchemy import create_engine, text
import warnings

warnings.filterwarnings("ignore")

st.set_page_config(page_title="AI Data Copilot", layout="wide")

st.title("🤖 AI Data Copilot")
st.markdown("Ask questions in natural language and get insights from your data instantly.")

st.markdown("### 💡 Try these questions:")
st.write("- Total amount by state")
st.write("- Show fraud transactions")
st.write("- Average transaction amount")

# ---------------------------
# DATA
# ---------------------------
data = {
    "id": [1, 2, 3, 4, 5, 6],
    "amount": [100, 200, 150, 300, 250, 180],
    "state": ["CA", "NY", "TX", "CA", "NY", "TX"],
    "category": ["fraud", "normal", "fraud", "normal", "fraud", "normal"]
}

df = pd.DataFrame(data)

engine = create_engine("sqlite:///data.db")
df.to_sql("transactions", engine, if_exists="replace", index=False)

# ---------------------------
# SQL LOGIC
# ---------------------------
def generate_sql(question):
    q = question.lower()

    if "total" in q and "state" in q:
        return "SELECT state, SUM(amount) as total_amount FROM transactions GROUP BY state"
    elif "fraud" in q:
        return "SELECT * FROM transactions WHERE category='fraud'"
    elif "average" in q:
        return "SELECT AVG(amount) as avg_amount FROM transactions"
    else:
        return "SELECT * FROM transactions"

def generate_explanation(question):
    q = question.lower()

    if "total" in q:
        return "This query calculates total transaction amount grouped by state."
    elif "fraud" in q:
        return "This query shows all fraud transactions."
    elif "average" in q:
        return "This query calculates average transaction amount."
    else:
        return "This query returns all records."

# ---------------------------
# FORM INPUT (ONLY THIS)
# ---------------------------
with st.form("query_form"):
    question = st.text_input("🔍 Ask your question:")
    submit = st.form_submit_button("Run Query")

# ---------------------------
# EXECUTION
# ---------------------------
if submit:

    if not question.strip():
        st.warning("Please enter a question")

    else:
        sql = generate_sql(question)

        try:
            with engine.connect() as conn:
                result = conn.execute(text(sql)).mappings().all()

            if result:
                result_df = pd.DataFrame(result)
            else:
                result_df = pd.DataFrame()
                st.warning("No data found")

            col1, col2 = st.columns(2)

            with col1:
                st.subheader("🧠 Generated SQL")
                st.code(sql)

                st.subheader("💡 Explanation")
                st.write(generate_explanation(question))

            with col2:
                st.subheader("📊 Results")
                st.dataframe(result_df)

            if (
                not result_df.empty and
                "state" in result_df.columns and
                "total_amount" in result_df.columns
            ):
                st.subheader("📈 Visualization")
                st.bar_chart(result_df.set_index("state"))

        except Exception as e:
            st.error(f"Error: {e}")

